reference

R for Data Science 
https://www.youtube.com/watch?v=NVyOEwOJgNQ&t=11820s

**Open this link in your browser to create a new notebook with R Kernel**

https://colab.research.google.com/notebook#create=true&language=r

# basics

###  math operations

In [ ]:
x<-18
print(x)
y<-4
z<-x+y
print(z)
z

[1] 18
[1] 22


[1] 22

In [ ]:
18+4
18-4
10/2
4.5/2

[1] 22

[1] 14

[1] 5

[1] 2.25

In [ ]:
#exp
2**3
2^3

[1] 8

[1] 8

In [ ]:
9**0.5

[1] 3

In [ ]:
9**1/2
#division operator has higher precision than exp=>first 9**1 then div by 2

[1] 4.5

In [ ]:
9**(1/2)

[1] 3

In [ ]:
14%%4 #modulus
14.75 %% 4

[1] 2

[1] 2.75

In [ ]:
8 / 3 #division
8 %/% 3 #integer division

[1] 2.666667

[1] 2

In [ ]:
-8 /3
-8 %/% 3
#integer division give floor value

[1] -2.666667

[1] -3

In [ ]:
TRUE+TRUE
FALSE+TRUE 

[1] 2

[1] 1

### VARIABLES 

In [ ]:
my_var=10
print(my_var)
my_var=20
typeof(my_var)
print(my_var)

[1] 10


[1] "double"

[1] 20


There are the following keywords as per ?reserved or help(reserved) command:

if	else	repeat
while	function	for
next	break	TRUE
FALSE	NULL	Inf
NaN	NA	NA_integer_
NA_real_	NA_complex_	NA_character_

``` 
if	else	repeat
while	function	for
next	break	TRUE
FALSE	NULL	Inf
NaN	NA	NA_integer_
NA_real_	NA_complex_	NA_character_
```



data types

In [ ]:
x<-10.25
x
class(x)

[1] 10.25

[1] "numeric"

Logical,Numeric,integer,complex,character,raw are the data types in R

In [ ]:
is.integer(x)
class(x)

[1] FALSE

[1] "numeric"

In [ ]:
x<-as.integer(10.25)
is.integer(x)
class(x)

[1] TRUE

[1] "integer"

In [ ]:
y<- 3 + 4i
class(y)
y

[1] "complex"

[1] 3+4i

In [ ]:
z<-TRUE
class(z)
z
z<-F
class(z)
z

[1] "logical"

[1] TRUE

[1] "logical"

[1] FALSE

variable assignment
<-  =  assign

In [ ]:
x<-10
assign('y',10)
x
y
z=100
z

[1] 10

[1] 10

[1] 100

In [ ]:
a<-b<-c<-66
a

[1] 66

In [ ]:
l<-letters
L<-LETTERS
print(l)
L

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"


[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

relational operators

` > < == <= >= !=`

logical 

& &&

|  ||

! not


In [ ]:
TRUE | FALSE

[1] TRUE

In [ ]:
10 & 0 #0 is treated as false
# 1 treated as true 
!10
!0

[1] FALSE

[1] FALSE

[1] TRUE

### sequences

In [ ]:
x<- 1:10 
x

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
x<- 1:10 -1
x

[1] 0 1 2 3 4 5 6 7 8 9

In [ ]:
x<-10
1:x
1:x-1 # first 1:x then subtract 1 from vector x
1:(x-1)

[1]  1  2  3  4  5  6  7  8  9 10

[1] 0 1 2 3 4 5 6 7 8 9

[1] 1 2 3 4 5 6 7 8 9

In [ ]:
y<-seq(6)
y
y<-seq(1,14)
y
yrev<-seq(from=10,to=1)
yrev

[1] 1 2 3 4 5 6

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14

[1] 10  9  8  7  6  5  4  3  2  1

In [ ]:
z<-seq(1,10,by=2)
print(z)
z<-seq(1,10,length=4)
print(z)

[1] 1 3 5 7 9
[1]  1  4  7 10


In [ ]:
s<-1:17
print(s)
s<-seq(1,10,2)#for odd
print(s)
s<-seq(0,10,2)#for even numbers
print(s)
s<-seq(10,0,-2)# for reverse
print(s)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17
[1] 1 3 5 7 9
[1]  0  2  4  6  8 10
[1] 10  8  6  4  2  0


In [ ]:
#replication
x<-rep(1,times=5)
print(x)
z<-rep('a',times=3)
print(z)

[1] 1 1 1 1 1
[1] "a" "a" "a"


In [ ]:
a<-1:3
print(a)
b<-rep(a,each=5)
print(b)

[1] 1 2 3
 [1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3


### if else

if (condition){

}


In [ ]:
x<-2
if (x > 0){
  print("positive")
}else if(x ==0 ){
print("it is zero")
} else {
  print("negative")
}

[1] "positive"


In [ ]:
x<-6
ifelse(x%%2 ==0,'even number','odd number')

[1] "even number"

### loops

In [ ]:
for(i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
for(i in 1:5)  print(i)


[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
x<-letters
y<-x[1:5]
#for (i in x) print(i)
for (i in y) print(i)

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"


In [ ]:
i<-1
while(i<=5){
  print(i)
  i<-i+1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


repeat loop

In [ ]:
i<-1
repeat{
  print(i)
  if(i>5)
   break
  i<-i+1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6


In [ ]:
for(i in 1:10){
  if(i%/% 2==0)
  next
  print(i)
}

[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


### Functions

In [ ]:
sum=function(a,b){
  c=a+b
  return(c)
}

In [ ]:
sum(6,-1)

[1] 5

In [ ]:
myeval=function(x,y){
  w=x+y
  z=x+y
  result=list('sum'=w,'mul'=z)
  return(result)
}

In [ ]:
myeval(10,20)

$sum
[1] 30

$mul
[1] 30

### lamda function in r


In [ ]:
mysum=function(x,y) x+y

In [ ]:
mysum(1,2)

[1] 3

# vectors

vector has elements of same datatype

c funtion for concatination ,creation of vector

In [ ]:
ve<-c(10,20,30)
ve

[1] 10 20 30

In [ ]:
assign('y',c(50,40,60))
print(y)

[1] 50 40 60

In [ ]:
lo<-c(T,F,T)
print(lo)

[1]  TRUE FALSE  TRUE


In [ ]:
e<-c(10,20,'a',3.5)
print(e)#because of vector coercion 
typeof(e)
length(e)

[1] "10"  "20"  "a"   "3.5"


[1] "character"

[1] 4

using 1:10 ,seq(1,10) we can create a vector

rep (10,3) create a vector 10 10 10 

In [ ]:
em<-vector()
print(em)

logical(0)


In [ ]:
z<-vector('numeric',length=4)
z

[1] 0 0 0 0

### indexing

In [ ]:
x<-c(67,55,105,10,40,35,40,80)
x
x[-2]
x[2:5]
x[c(1,2,4,6)]

[1]  67  55 105  10  40  35  40  80

[1]  67 105  10  40  35  40  80

[1]  55 105  10  40

[1] 67 55 10 35

In [ ]:
x[2]<-8
x
#to replace/overwrite with 8

[1]  67   8 105  10  40  35  40  80

In [ ]:
x[-3]<-0
x
#for -ve index except that all the other elements are replaced

[1]   0   0 105   0   0   0   0   0

In [ ]:
x<-c(10,20,30,40,50,60)
y<-c(T,F,T,T,T,F,T)
x[y]#

[1] 10 30 40 50 NA

In [ ]:
x<-c(10,20,30,40,50,60)
y<-c(T,F,T)
x[y]#as the length of y is less than x . y vector is extended in round robin fashion

[1] 10 30 40 60

In [ ]:
#matching operator %in%
35 %in% x
30 %in% x

[1] FALSE

[1] TRUE

### arithematic operations

In [ ]:
x<-c(10,20,30,100)
x
sqrt(x)
y<-x-10
y

[1]  10  20  30 100

[1]  3.162278  4.472136  5.477226 10.000000

[1]  0 10 20 90

In [ ]:
rev(y)#reverse
sort(y)
x %*% y


[1] 90 20 10  0

[1]  0 10 20 90

[,1]
[1,] 9800

In [ ]:
crossprod(x,y)

[,1]
[1,] 9800

In [ ]:
x %o% y

[,1] [,2] [,3] [,4]
[1,] 0     100  200  900
[2,] 0     200  400 1800
[3,] 0     300  600 2700
[4,] 0    1000 2000 9000

In [ ]:
out<- x> 10 & x<50
out
x[out]

[1] FALSE  TRUE  TRUE FALSE

[1] 20 30

In [ ]:
index<-which(x>20)
index
x[index]

[1] 3 4

[1]  30 100

### factor

In [ ]:
x<-factor(c("male","female","male","female","male","male","female","male"))
x
table(x)

[1] male   female male   female male   male   female male  
Levels: female male

x
female   male 
     3      5 

Mathematical operations

In [ ]:
x<-c(3.66,6.78,9.101,-1.01)
abs(x)
ceiling(x)
floor(x)
round(x)
round(x,1)

[1] 3.660 6.780 9.101 1.010

[1]  4  7 10 -1

[1]  3  6  9 -2

[1]  4  7  9 -1

[1]  3.7  6.8  9.1 -1.0

[1]  3  6  9 -1

In [ ]:
x<-c(3.66,6.78,9.101,-1.01)
trunc(x)

[1]  3  6  9 -1

In [ ]:
x<-c(3.66,6.78,9,10)
sqrt(x)
exp(x)
log(x)
log(x,base=10)
log10(x)

[1] 1.913113 2.603843 3.000000 3.162278

[1]    38.86134   880.06872  8103.08393 22026.46579

[1] 1.297463 1.913977 2.197225 2.302585

[1] 0.5634811 0.8312297 0.9542425 1.0000000

[1] 0.5634811 0.8312297 0.9542425 1.0000000

In [ ]:
factorial(5)

[1] 120

### random numbers

In [ ]:
r<-rnorm(10)
r#mean=0,std=1

[1]  2.1608776  0.9930759  0.9147426  0.2748140 -1.8742311 -0.8091658
 [7] -1.4702915 -0.7095577 -0.9110689  1.6532014

In [ ]:
y<-rnorm(10,mean=2,sd=1)
y

[1] 2.6237787 1.1807167 2.7357963 2.6502388 3.1137720 0.4817669 3.1648060
 [8] 2.0615122 1.1552406 1.8859553

# matrix

matrix are created in columnwise

In [ ]:
m<-matrix(nrow=2,ncol=3)
m
dim(m)

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

[1] 2 3

In [ ]:
m<-matrix(c(1,2,3,4,5,6))
print(m)

     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4
[5,]    5
[6,]    6


In [ ]:
m<-matrix(c(1,2,3,4,5,6),nrow=2,ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


*by row is used for row wise*

In [ ]:
m<-matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=T)
print(m)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


In [ ]:
m<-matrix(1:12,nrow=4,ncol=3,byrow=T)
print(m)
length(m)
dim(m)
nrow(m)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


[1] 12

[1] 4 3

[1] 4

matrix diag()

In [ ]:
d<-matrix(1,3,3)
print(d)

     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
[3,]    1    1    1


In [ ]:
m<-diag(1:5)
print(m)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5


In [ ]:
rownames(m)<-c(10,20,30,40,50)
colnames(m)<-c("A","B","C","D","E")
m

A B C D E
10 1 0 0 0 0
20 0 2 0 0 0
30 0 0 3 0 0
40 0 0 0 4 0
50 0 0 0 0 5

### *matrix* indexing

In [ ]:
m[3,]
m

A B C D E 
0 0 3 0 0

In [ ]:
A<-matrix(c(2,3,4,0,5,7,5,8,2,1,-1,-2),nrow = 4,ncol = 3,byrow = T)
print(A)
A[3,2:3]=80
A
print(A)

     [,1] [,2] [,3]
[1,]    2    3    4
[2,]    0    5    7
[3,]    5    8    2
[4,]    1   -1   -2


[,1] [,2] [,3]
[1,] 2     3    4  
[2,] 0     5    7  
[3,] 5    80   80  
[4,] 1    -1   -2

     [,1] [,2] [,3]
[1,]    2    3    4
[2,]    0    5    7
[3,]    5   80   80
[4,]    1   -1   -2


In [ ]:
diag(A)
print(diag(A))

[1]  2  5 80

[1]  2  5 80


In [ ]:
b<-rbind(A,c(10,11,12))
print(b)

     [,1] [,2] [,3]
[1,]    2    3    4
[2,]    0    5    7
[3,]    5   80   80
[4,]    1   -1   -2
[5,]   10   11   12


In [ ]:
c<-rbind(A,b)
print(c)

      [,1] [,2] [,3]
 [1,]    2    3    4
 [2,]    0    5    7
 [3,]    5   80   80
 [4,]    1   -1   -2
 [5,]    2    3    4
 [6,]    0    5    7
 [7,]    5   80   80
 [8,]    1   -1   -2
 [9,]   10   11   12


In [ ]:
D<-cbind(A,c(10,11,12))
print(D)

Warning message in cbind(A, c(10, 11, 12)):
“number of rows of result is not a multiple of vector length (arg 2)”


     [,1] [,2] [,3] [,4]
[1,]    2    3    4   10
[2,]    0    5    7   11
[3,]    5   80   80   12
[4,]    1   -1   -2   10



for rbind,cbind dimensions has to be match


### matrix operations

In [ ]:
A<-matrix(c(1,2,3,4,5,6,7,8,9),nrow = 3,ncol = 3,byrow = T)
print(A)
B<-matrix(c(1,2,3,4,5,6,7,8,9),nrow = 3,ncol = 3)
print(B)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [ ]:
C=A+B
print(C)

     [,1] [,2] [,3]
[1,]    2    6   10
[2,]    6   10   14
[3,]   10   14   18


In [ ]:
print(A-B)
print(A*B) #element wise multplication
print(A %*%B ) #matrix multplication
print(A/B)

     [,1] [,2] [,3]
[1,]    0   -2   -4
[2,]    2    0   -2
[3,]    4    2    0
     [,1] [,2] [,3]
[1,]    1    8   21
[2,]    8   25   48
[3,]   21   48   81
     [,1] [,2] [,3]
[1,]   14   32   50
[2,]   32   77  122
[3,]   50  122  194
         [,1]     [,2]      [,3]
[1,] 1.000000 0.500000 0.4285714
[2,] 2.000000 1.000000 0.7500000
[3,] 2.333333 1.333333 1.0000000


In [ ]:
t(A)#transverse of A

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

https://cran.r-project.org/web/packages/matlib/vignettes/inv-ex1.html
refer this for more math operations like det

In [ ]:
print(A)
rowSums(A)
colSums(A)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


[1]  6 15 24

[1] 12 15 18

In [ ]:
rowMeans(A)

[1] 2 5 8

In [ ]:
colMeans(A)

[1] 4 5 6

In [ ]:
apply(A,1,sum)#1 for row
apply(A,2,sum) #2 for col

[1]  6 15 24

[1] 12 15 18

# LIST

In [ ]:
x<-list(1,"karthik",105.67)
x

[[1]]
[1] 1

[[2]]
[1] "karthik"

[[3]]
[1] 105.67

In [ ]:
rollno<-c(101,102,103,104,105)
snames<-c('john','bob','alice')
marks<-c(78.25,100,90.2)
student<-list(rollno,snames,marks)
student
print(student)

[[1]]
[1] 101 102 103 104 105

[[2]]
[1] "john"  "bob"   "alice"

[[3]]
[1]  78.25 100.00  90.20

[[1]]
[1] 101 102 103 104 105

[[2]]
[1] "john"  "bob"   "alice"

[[3]]
[1]  78.25 100.00  90.20



the above is example for list with different datatypes,sizes
 

In [ ]:
print(student[1])
print(student[[1]])

[[1]]
[1] 101 102 103 104 105

[1] 101 102 103 104 105


In [ ]:
# $
student<-list('id'=rollno,'name'=snames,'scores'=marks)
print(student$scores)
print(student[c('id')])
print("----- ----- -----")
print(student[1:3])

[1]  78.25 100.00  90.20
$id
[1] 101 102 103 104 105

[1] "----- ----- -----"
$id
[1] 101 102 103 104 105

$name
[1] "john"  "bob"   "alice"

$scores
[1]  78.25 100.00  90.20



list concat

In [ ]:
rollno<-c(101,102,103,104,105)
snames<-c('john','bob','alice')
marks<-c(78.25,100,90.2)
student<-list(rollno,snames,marks)
age<-list(c(19,20,18))
students<-c(student,age)
print(students)

[[1]]
[1] 101 102 103 104 105

[[2]]
[1] "john"  "bob"   "alice"

[[3]]
[1]  78.25 100.00  90.20

[[4]]
[1] 19 20 18



In [ ]:
print(student)#this is the list created before

[[1]]
[1] 101 102 103 104 105

[[2]]
[1] "john"  "bob"   "alice"

[[3]]
[1]  78.25 100.00  90.20



# DATAFRAMES


In [ ]:
id<-c(101,102,103)
names<-c('john','bob','alice')
marks<-c(78.25,100,90.2)
stu<-data.frame(id,names,marks)
stu

id  names marks 
1 101 john   78.25
2 102 bob   100.00
3 103 alice  90.20

In [ ]:
print(stu[2,])
print(stu[2:3,])

   id names marks
2 102   bob   100
   id names marks
2 102   bob 100.0
3 103 alice  90.2


In [ ]:
print(stu[,1])

[1] 101 102 103


In [ ]:
print(stu[2:3,1:3])

   id names marks
2 102   bob 100.0
3 103 alice  90.2


In [ ]:
print(stu[-2,-3])#to remove we use -

   id names
1 101  john
3 103 alice


In [ ]:
print(stu[[2]][1])
print(stu$id)
print(stu$id[1])

[1] "john"
[1] 101 102 103
[1] 101


subset()

In [ ]:
id<-c(101,102,103)
names<-c('john','bob','alice')
marks<-c(78.25,100,90.2)
stu<-data.frame(id,names,marks)
#stu
report<-subset(stu,marks>90)
print(report)

   id names marks
2 102   bob 100.0
3 103 alice  90.2


In [ ]:
report<-subset(stu,marks>90,select=c(names,marks))
print(report)

  names marks
2   bob 100.0
3 alice  90.2


rbind,cbind in dataframe

In [ ]:
stud<-rbind(stu,data.frame(id=104,names='vk',marks=80.52))
stud

id  names marks 
1 101 john   78.25
2 102 bob   100.00
3 103 alice  90.20
4 104 vk     80.52

In [ ]:
stud<-cbind(stu,age=c(18,19,20))
stud

id  names marks  age
1 101 john   78.25 18 
2 102 bob   100.00 19 
3 103 alice  90.20 20

edit()

In [ ]:
stutable<-edit(stu)
stutable

ERROR: ignored

missing dat

In [ ]:
x<-c(10,NA,45.6)
is.na(x)

[1] FALSE  TRUE FALSE

In [ ]:
x<-c(10,NA,45.6,NaN)
y<-is.nan(x)
y

[1] FALSE FALSE FALSE  TRUE

In [ ]:
x[!y]#removed nan

[1] 10.0   NA 45.6

In [ ]:
id<-c(101,102,103,104,105)
temp<-c(25.8,34.2,NA,27.4,20.5)
wind<-c(25,45,78,40,68)
humidity<-c(25,45,85,NA,61)
weather<-data.frame(id,temp,wind,humidity)
print(weather)

   id temp wind humidity
1 101 25.8   25       25
2 102 34.2   45       45
3 103   NA   78       85
4 104 27.4   40       NA
5 105 20.5   68       61


In [ ]:
weatherNA<-complete.cases(weather)
weatherNA
print(weather[weatherNA,])

[1]  TRUE  TRUE FALSE FALSE  TRUE

   id temp wind humidity
1 101 25.8   25       25
2 102 34.2   45       45
5 105 20.5   68       61
